### ISSUE TITLE
String does not match the pattern of "DEPRECATED^"

### ISSUE THREAD

**Issue by NCSUholmey** [adt-pulse-mqtt/adt-pulse-mqtt#56]
working off of 3.1.1 and noticed an error in my configuration.yaml file within the past couple of weeks:

binary_sensor:
  - platform: mqtt
    name: "Kitchen Door"     String does not match the pattern of "DEPRECATED^"
    state_topic: "adt/zone/Kitchen Door/state"     String does not match the pattern of "DEPRECATED^"
    payload_on: "devStatOpen"     String does not match the pattern of "DEPRECATED^"
    payload_off: "devStatOK"     String does not match the pattern of "DEPRECATED^"
    device_class: door     String does not match the pattern of "DEPRECATED^"

any help on ways to fix?

i've gotten the alarm_control_panel updated but somehow cant clear my sensors.

**Comment by digitalcraig** [comment]
It looks like there was a breaking change in 2022.6 of Home Assistant:

"Defining manually configured MQTT entities directly under the respective platform keys (e.g., fan, light, sensor, etc.) is deprecated, and support will be removed in Home Assistant Core 2022.9. Manually configured MQTT entities should now be defined under the mqtt configuration key in configuration.yaml instead of under the platform key."

See the updated [Documentation](https://www.home-assistant.io/integrations/binary_sensor.mqtt)

So your configuration.yaml would now look like this:

```
mqtt:
  binary_sensor:
    - name: "Kitchen Door" 
      state_topic: "adt/zone/Kitchen Door/state"
      payload_on: "devStatOpen"
      payload_off: "devStatOK" 
      device_class: door 
```
