### ISSUE TITLE
Arming requires a code but none was given for alarm_control_panel.adt_pulse

### ISSUE THREAD

**Issue by ryanbuckner** [adt-pulse-mqtt/adt-pulse-mqtt#66]
I believe this is a new requirement from the base libraries but since there is no unique_id the "Code" cannot be added in the UI. Does anyone know how I can add the code in the yaml without causing a security issue? 
.

![Image](https://github.com/user-attachments/assets/3711ff5b-53bb-4924-8bbc-00082b846881)

![Image](https://github.com/user-attachments/assets/1e76dab7-d48b-4d30-9941-1adb13d51652)

Here's the yaml for the control panel from the documentation. But there's no documentation on how to send commands. 

```
mqtt:
  alarm_control_panel:
    - name: "ADT Pulse"
      state_topic: "home/alarm/state"
      command_topic: "home/alarm/cmd"
      payload_arm_home: "arm_home"
      payload_arm_away: "arm_away"
      payload_disarm: "disarm"
```

**Comment by Wolfang42** [comment]
I've this same issue...cannot find a solution.

**Comment by BigThunderSR** [comment]
My fork still works: https://github.com/BigThunderSR/adt-pulse-mqtt

**Comment by Wolfang42** [comment]
> My fork still works: https://github.com/BigThunderSR/adt-pulse-mqtt

I am using your fork...still getting same error for some reason.

**Comment by BigThunderSR** [comment]
> > My fork still works: https://github.com/BigThunderSR/adt-pulse-mqtt
> 
> I am using your fork...still getting same error for some reason.

Have you added the last part of the YAML in the instructions in this section? 

`To add the control panel:`

**Comment by Wolfang42** [comment]
> > > My fork still works: https://github.com/BigThunderSR/adt-pulse-mqtt
> > 
> > 
> > I am using your fork...still getting same error for some reason.
> 
> Have you added the last part of the YAML in the instructions in this section?
> 
> `To add the control panel:`

Yes sir, cut and pasted into my configuration.yaml. No change.

**Comment by BigThunderSR** [comment]
> > > > My fork still works: https://github.com/BigThunderSR/adt-pulse-mqtt
> > > 
> > > 
> > > I am using your fork...still getting same error for some reason.
> > 
> > 
> > Have you added the last part of the YAML in the instructions in this section?
> > `To add the control panel:`
> 
> Yes sir, cut and pasted into my configuration.yaml. No change.

To confirm, do you have `code_arm_required: false ` in the config?

```yaml
mqtt:
   alarm_control_panel:
     - name: "ADT Pulse"
       state_topic: "home/alarm/state"
       command_topic: "home/alarm/cmd"
       payload_arm_home: "arm_home"
       payload_arm_away: "arm_away"
       payload_disarm: "disarm"
       code_arm_required: false  ## Needs to be added starting with HA Core 2024.6 ##
```
